# Imports

In [13]:
import pandas as pd 
# import matplotlib as plt

In [4]:
df = pd.read_csv("PC_0.txt",sep="\t")

In [5]:
df.head()

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,F_MISS,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF
0,rs3131962,1,756604,0.004907,A,G,0.135889,0.002010,4.354290,0.037,0.001238,0.000678,3.334050,0.068
1,rs115991721,1,767096,0.004951,A,G,0.998881,0.002010,0.151903,0.700,0.002507,0.006889,0.132475,0.720
2,rs12562034,1,768448,0.004957,G,A,0.891876,0.001935,0.325677,0.570,0.000217,0.000747,0.084324,0.770
3,rs79373928,1,801536,0.005872,T,G,0.986134,0.000670,0.154278,0.690,0.000865,0.001990,0.188855,0.660
4,rs11240779,1,808631,0.006208,G,A,0.236136,0.008138,0.074229,0.790,0.000088,0.000548,0.026072,0.870

In [19]:
correlation = df.loc[df['P_BOLT_LMM_INF'] <= 0.00000001]

In [20]:
correlation

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,F_MISS,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF
466229,rs9930506,16,53830465,0.646083,A,G,0.568986,0.013125,31.7667,1.700000e-08,-0.002819,0.000475,35.2589,2.900000e-09